### ISSUE TITLE
Apache license mentioned in mvnw.cmd

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/smartclide-service-creation#1]
The Apache license is mentioned in the file mvnw.cmd when the rest of the repository in mentioning the EPL 2.0 license.
I suspect a copy/péste error

Kind regards

**Comment by nikosnikolaidis** [comment]
It was an auto generated Maven Wrapper file, which is not important.
Forgot to link the commit [f9aea98] to this issue.
